version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Expose FastAPI port
    volumes:
      - .:/app  # Mount current directory to /app inside the container
    environment:
      - ENVIRONMENT=development
    tty: true  # Keep the container running